Employee Class Reference
This class keeps up with information related to the employee, such as their employee ID and how many years they have worked.
#include `employee/Employee.h`
Public Member Functions
virtual void print ()
virtual double calculatePay ()
void anniversary ()
Employee ()
Employee (int ID, int years, double hourlyRate, float hoursWorked)
Protected Attributes
double hourlyRate
float hoursWorked
Private Attributes
int ID
int years
Detailed Description
This class keeps up with information related to the employee, such as their employee ID and how many years they have worked.
The Employee class -- this is how the company keeps track of the info on their employees
Constructor & Destructor Documentation
Employee() [1/2]
Employee::Employee ()
this is the default constructor
Precondition
N/A
Postcondition
the employee class is created with all of the member variables being set to -1
The constructor for the employee class
Precondition
This sets up the member variables of the employee class
Postcondition
The member variables areae all initialized to -1
Employee() [2/2]
Employee::Employee (int ID, int years, double hourlyRate, float hoursWorked)
this is the parameterized constructor
Parameters
int ID this is the employee id
int years the number of years that an employee has worked at the company
double hourlyRate The hourly rate that the employee is paid at
float hoursWorked the number of hours that the employee has worked in the pay period
Precondition
N/A
Postcondition
The member variables are set to whatever the user specifies in the constructor.
The paramaterized constructor for the employee class
Parameters
int ID the employee id
int years the number of years that they have worked for the company
double hourlyRate the amount the employee gets paid per hour
float hoursWorked the number of hours that an employee has worked
Precondition
This function takes the member variables and sets them equal to the values passed in the arguments section
Postcondition
the member variables are set equal to whatever is in the parenthesis
Member Function Documentation
anniversary()
void Employee::anniversary ()
This function is for celebrating the anniversiary of an employee working at the company
Precondition
N/A -- this function does not need anything to be true, it can be called whenever the user decides
Returns
void this function doesn't return anything, it just adjusts the employee's pay and prints out a celebratory message.
Postcondition
The employee's pay is slightly bumped up and they are congratualed for their years of work
This function is for celebrating x amount of years an employee works
Precondition
An employee object must exist for us to be able to call this funciton
Returns
void This funciton raises the employee
Postcondition
This funciton raises the employee's hourly rate and congratulates them for their years of work
Referenced by runEmployeeTests().
calculatePay()
double Employee::calculatePay () [virtual]
This function calculates the pay that an employee is owed
Precondition
The information (such as hourly rate and hours worked) needs to be entered already
Returns
virtual No return type--this function only calculates the pay that the employee is owed
Postcondition
The employee's pay is printed out
This function calculates the amount of pay that an employee is owed
Precondition
This function requires that an employee has already entered in the information about how long they have worked
Returns
double This function returns the dollar amount that an employee is owed.
Postcondition
The dollar amount for the next paycheck is printed out
Reimplemented in Officer, and Supervisor.
Referenced by Supervisor::calculatePay(), and runEmployeeTests().
print()
void Employee::print () [virtual]
This is the print function
Precondition
An existing and populated instance of the employee class must exist
Returns
virtual no return type, this function just prints out details
Postcondition
The details of the employee class instance are printed out
This function prints out the employee info
Precondition
A valid entry for an employee must already exist
Returns
void This function doesn't return anything, it just prints out what is already in the employee object
Postcondition
The details of the employee object is printed out
Reimplemented in Officer, and Supervisor.
Referenced by Officer::print(), Supervisor::print(), and runEmployeeTests().
The documentation for this class was generated from the following files:
employee/Employee.h
employee/Employee.cpp